AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vanity-number-app

  Template for vanity-number-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:    
  ConvertNumberFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: dist/
        Handler: convert-number.handler
        Runtime: nodejs14.x
        Policies: AmazonDynamoDBFullAccess

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties: 
      PrimaryKey: 
        Name: phone_number
        Type: String
      TableName: VANITY_NUMBERS

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ConvertNumberFunction:
    Description: "Convert Number Lambda Function ARN"
    Value: !GetAtt ConvertNumberFunction.Arn
  ConvertNumberFunctionIamRole:
    Description: "Implicit IAM Role created for Convert Number function"
    Value: !GetAtt ConvertNumberFunctionRole.Arn
